name: Python Package Using Conda

on:
  push:
    branches: [ "matt/conda" ]

permissions:
  contents: read

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [  '3.9' ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        # $CONDA/bin/conda env update --file environment.yml --name base
        $CONDA/bin/conda install mamba -n base -c conda-forge
        $CONDA/bin/mamba env update -f environment.yaml -n base 
    - name: Install detectree2 
      run: | 
        pip install .

